In [4]:
import numpy as np
ar_1 = np.array([[1, 2], [3, 4]])  #No of Rows: 2 No of Col.: 2
ar_2 = np.array([[5, 6]])  #No of Rows: 1 No of Col.: 2
ar_3 = np.concatenate((ar_1, ar_2), axis=None)
print(ar_3, end = '\n\n')


[1 2 3 4 5 6]



In [5]:
ar_6 = np.array((1,2,3))  #No of Rows: 1 No of Col.: 3
ar_7 = np.array((4,5,6))  #No of Rows: 1 No of Col.: 3
ar_8 = np.hstack((ar_6, ar_7))
print(ar_8) 


[1 2 3 4 5 6]


In [6]:
a = np.array([[1, 2],[3, 4]])  #No of Rows: 2 No of Col.: 2
b = np.array([[5, 6],[7, 8]])  #No of Rows: 2 No of Col.: 2   
c = np.hstack((a, b))
print(c) 


[[1 2 5 6]
 [3 4 7 8]]


In [7]:
ar_9 = np.array([[1],[2],[3]])  #No of Rows: 3 No of Col.: 1
ar_10 = np.array([[4],[5],[6]])  #No of Rows: 3 No of Col.: 1
ar_11 = np.hstack((ar_9, ar_10))
print(ar_11) 


[[1 4]
 [2 5]
 [3 6]]


In [8]:
ar_12 = np.array([1, 2, 3])  #No of Rows: 1 No of Col.: 3
ar_13 = np.array([4, 5, 6])  #No of Rows: 1 No of Col.: 3
ar_14 = np.vstack((ar_12, ar_13))
print(ar_14)


[[1 2 3]
 [4 5 6]]


In [9]:
ar_15 = np.array([[1],[2],[3]])  #No of Rows: 3 No of Col.: 1
ar_16 = np.array([[4],[5],[6]])  #No of Rows: 3 No of Col.: 1
ar_17 = np.vstack((ar_15, ar_16))
print(ar_17) 


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [12]:
ar_18 = np.array([1, 2, 3])   #No of Rows: 1 No of Col.: 3
ar_19 = np.array([4, 5, 6])   #No of Rows: 1 No of Col.: 3
# ar_20  = np.stack((ar_18, ar_19)) #The default value for the axis is 0.
ar_21 = np.stack((ar_18, ar_19), axis = 1)
print(ar_21, end = '\n\n')



TypeError: 'NoneType' object cannot be interpreted as an integer

In [13]:
ar_22 = np.array([[1,2,3], [4,5,6]])   #No of Rows: 2 No of Col.: 3
ar_23 = np.array([[7,8,9], [10,11,12]])   #No of Rows: 2 No of Col.: 3

ar_24 = np.stack((ar_22,ar_23), axis = 0)   #No of depth: 2 No of Rows: 2 No of Col.: 3
ar_25 = np.stack((ar_22,ar_23), axis = 1)   #No of depth: 2 No of Rows: 2 No of Col.: 3

print(ar_24, end = '\n\n')
print(ar_25, end = '\n\n')


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]



In [20]:
import numpy as np
ar_1 = np.arange(24.0).reshape(4, 6)
print(ar_1)
# print(np.hsplit(ar_1, 4), end = "\n\n")
print(np.vsplit(ar_1, 4), end = "\n\n")




[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[array([[0., 1., 2., 3., 4., 5.]]), array([[ 6.,  7.,  8.,  9., 10., 11.]]), array([[12., 13., 14., 15., 16., 17.]]), array([[18., 19., 20., 21., 22., 23.]])]

