In [3]:

import numpy as np
ar_1 = np.array([10, 20, 30, 40, 50])
print(ar_1)

ar_2 = np.array([10, 20, 30, 40, 50], dtype = float)
print(ar_2)

ar_3 = np.array([1, 2, '3', 4])
print(ar_3)

ar_4 = np.array([[10, 20], [100, 90]])
print(ar_4)


print("The dimension of ", ar_3, "is", ar_3.ndim)
print("The dimension of ", ar_4, "is", ar_4.ndim)

print("The shape of ", ar_3, "is", ar_3.shape)
print("The shape of ", ar_4, "is", ar_4.shape)




[10 20 30 40 50]
[10. 20. 30. 40. 50.]
['1' '2' '3' '4']
[[ 10  20]
 [100  90]]
The dimension of  ['1' '2' '3' '4'] is 1
The dimension of  [[ 10  20]
 [100  90]] is 2
The shape of  ['1' '2' '3' '4'] is (4,)
The shape of  [[ 10  20]
 [100  90]] is (2, 2)


In [5]:
b = [1,2,3,4,5]
print(b[:-1])

[1, 2, 3, 4]


In [10]:
a = np.array([[1,2,3], [4,5,6], [9,8,7]])
print(a.ndim)

2


In [11]:
ar_11 = np.arange(10, 25, 2)
print(ar_11)
print("ar_11[1] =",ar_11[1])



[10 12 14 16 18 20 22 24]
ar_11[1] = 12


In [14]:
ar_12 = np.array([np.arange(21, 10, -2), np.arange(10, -1, -2), np.zeros(6, dtype = np.int64)])
print(ar_12)
print("ar_12[0, 0] =",ar_12[0, 0]) # 21
print("ar_12[-1,- 2] =",ar_12[-1,- 2]) # 0
print("ar_12[0, 0:6:2] =",ar_12[0, 0:6:2]) #[21 17 13]
print("ar_12[1:2, 5:0:-2] =",ar_12[1:2, 5:0:-2]) #[[0 4 8]]
print("ar_12[-2::-1, -3:-1] =",ar_12[-2::-1, -3:-1]) #[[ 4  2] [15 13]]


[[21 19 17 15 13 11]
 [10  8  6  4  2  0]
 [ 0  0  0  0  0  0]]
ar_12[0, 0] = 21
ar_12[-1,- 2] = 0
ar_12[0, 0:6:2] = [21 17 13]
ar_12[1:2, 5:0:-2] = [[0 4 8]]
ar_12[-2::-1, -3:-1] = [[ 4  2]
 [15 13]]


In [16]:
a = np.empty((2, 3))
print(a)

[[5.e-323 4.e-323 3.e-323]
 [2.e-323 1.e-323 0.e+000]]
