In [8]:
import numpy as np
ar_1 = np.array([[1,4],
                 [3,1]])
# ar_2 = np.sort(ar_1)
# ar_3 = np.sort(ar_1, axis=0)
# print(ar_2)
# print()
# print(ar_3)
ar_4 = np.sort(ar_1, axis = None)
print(ar_4)



[1 1 3 4]


In [12]:
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]
dtype = [('name', 'U10'), ('height', float), ('age', int)]
ar_5 = np.array(values, dtype=dtype)
print(ar_5, end = '\n\n')
ar_6 = np.sort(ar_5, order=['age', 'height'])
print(ar_6, end = '\n\n')



[('Arthur', 1.8, 41) ('Lancelot', 1.9, 38) ('Galahad', 1.7, 38)]

[('Galahad', 1.7, 38) ('Lancelot', 1.9, 38) ('Arthur', 1.8, 41)]



In [13]:
import pandas as pd
import numpy as np
series1 = pd.Series([10,20,30])
print(series1)


0    10
1    20
2    30
dtype: int64


In [19]:
array1 = np.arange(10, 31, 5)
series2 = pd.Series(array1)
print(series2)
arr = series6 .to_numpy()
print(arr)
print(arr.dtype)



0    10
1    15
2    20
3    25
4    30
dtype: int64
['NewDelhi' 'London' 'Tokyo' nan]
object


In [15]:
series3 = pd.Series(["Kavi", "Shyam", "Ravi"], index=[3, 5,1])
print(series3)


3     Kavi
5    Shyam
1     Ravi
dtype: object


In [17]:
dict1 = {'India': 'NewDelhi', 'UK': 'London', 'Japan': 'Tokyo'}
series5 = pd.Series(dict1, index=[3, 5,1])
print(series5)


3    NaN
5    NaN
1    NaN
dtype: object


In [18]:
dict1 = {'India': 'NewDelhi', 'UK': 'London', 'Japan': 'Tokyo'}
series6 = pd.Series(dict1, index = ['India', 'UK', 'Japan', 'France'])
print(series6)


India     NewDelhi
UK          London
Japan        Tokyo
France         NaN
dtype: object


In [25]:
country_cap_series = pd.Series(['NewDelhi', 'WashingtonDC', 'London', 'Paris'], index=['India', 'USA', 'UK', 'France'])
print(country_cap_series['India'])
print(country_cap_series[0:3])
print(country_cap_series['India':'France'])
country_cap_series[0:2] = 'abc'
print(country_cap_series)


NewDelhi
India        NewDelhi
USA      WashingtonDC
UK             London
dtype: object
India         NewDelhi
USA       WashingtonDC
UK              London
France           Paris
dtype: object
India        abc
USA          abc
UK        London
France     Paris
dtype: object


In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
result = a + b
print(result)


[[11 22 33]
 [14 25 36]]
