In [14]:
import numpy as np 
import pandas as pd

dictForest = {'State': ['Assam', 'Delhi', 'Kerala'], 'GArea': [78438, 1483, 38852] ,'VDF' : [2797, 6.72,1663]}
dFrame4 = pd.DataFrame(dictForest)
print(dFrame4)

dFrame5 = pd.DataFrame(dictForest, columns = ['State','VDF', 'GArea'])
print(dFrame5)



    State  GArea      VDF
0   Assam  78438  2797.00
1   Delhi   1483     6.72
2  Kerala  38852  1663.00
    State      VDF  GArea
0   Assam  2797.00  78438
1   Delhi     6.72   1483
2  Kerala  1663.00  38852


In [3]:
seriesA = pd.Series([1,2,3,4,5], index = ['a', 'b', 'c', 'd', 'e'])
seriesB = pd.Series ([1000,2000,-1000,-5000,1000], index = ['a', 'b', 'c', 'd', 'e'])
seriesC = pd.Series([10,20,-10,-50,100], index = ['z', 'y', 'a', 'c', 'e'])
dFrame6 = pd.DataFrame([seriesA, seriesB, seriesC])
print(dFrame6)


        a       b       c       d       e     z     y
0     1.0     2.0     3.0     4.0     5.0   NaN   NaN
1  1000.0  2000.0 -1000.0 -5000.0  1000.0   NaN   NaN
2   -10.0     NaN   -50.0     NaN   100.0  10.0  20.0


In [5]:
ResultSheet={
  'Arnab': pd.Series([90, 91, 97], index=['Maths','Science','Hindi']),
  'Ramit': pd.Series([92, 81, 96], index=['Maths','Science','Hindi']),
  'Samridhi': pd.Series([89, 91, 88], index=['Maths','Science','Hindi']), 
  'Riya': pd.Series([81, 71, 67], index=['Maths','Science','Hindi']),
  'Mallika': pd.Series([94, 95, 99], index=['Maths','Science','Hindi'])
}
dFrame7 = pd.DataFrame(ResultSheet)
print(dFrame7)
print(dFrame7.to_numpy())


         Arnab  Ramit  Samridhi  Riya  Mallika
Maths       90     92        89    81       94
Science     91     81        91    71       95
Hindi       97     96        88    67       99
[[90 92 89 81 94]
 [91 81 91 71 95]
 [97 96 88 67 99]]


In [12]:
array_2D = [np.arange(1, 5, 1), np.arange(10, 6, -1), np.arange(15, 12, -1)]
dFrame8 = pd.DataFrame(array_2D,
                       index = ['R1', 'R2', 'R3'],
                       columns = ['C1', 'C2', 'C3', 'C4'])
print(dFrame8)
# dFrame8.info()
dFrame9 = dFrame8.rename({'R1':'Sub1', 'R2':'Sub2','R3':'Sub3'}, axis='index')
print(dFrame9)


    C1  C2  C3   C4
R1   1   2   3  4.0
R2  10   9   8  7.0
R3  15  14  13  NaN
      C1  C2  C3   C4
Sub1   1   2   3  4.0
Sub2  10   9   8  7.0
Sub3  15  14  13  NaN


In [11]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, np.nan, 35],
    'City': ['New York', 'Paris', 'London']
}

df = pd.DataFrame(data)
print(df)
# print("df.index :", df.index)
# print("df.columns :", df.columns)
# print("df.values :\n", df.values)
# print("df.T :\n", df.T)


print("df.dtypes :\n", df.dtypes)
print("\ndf.shape :", df.shape)
print("df.size :", df.size)
print("df.empty :", df.empty)


      Name   Age      City
0    Alice  25.0  New York
1      Bob   NaN     Paris
2  Charlie  35.0    London
df.dtypes :
 Name     object
Age     float64
City     object
dtype: object

df.shape : (3, 3)
df.size : 9
df.empty : False


In [23]:
ResultSheet = {
  'Arnab': pd.Series([90, 91, 97], index=['Maths','Science','Hindi']),
  'Ramit': pd.Series([92, 81, 96], index=['Maths','Science','Hindi']),
  'Samridhi': pd.Series([89, 91, 88], index=['Maths','Science','Hindi']), 
  'Riya': pd.Series([81, 71, 67], index=['Maths','Science','Hindi']),
  'Mallika': pd.Series([94, 95, 99], index=['Maths','Science','Hindi'])
}
dFrame1 = pd.DataFrame(ResultSheet)
print(dFrame1)

# print(dFrame1.at['Maths', 'Samridhi'], end = '\n\n')

# print(dFrame1.iat[0, 2], end = '\n\n')
# print(dFrame1['Arnab'])

# print(dFrame1[['Arnab', 'Riya']])

# print(dFrame1['Maths' : 'Science'])
# print(dFrame1.iloc[0])
# print(dFrame1.loc['Science'])

# print(dFrame1.loc[:,'Arnab'])
# print(dFrame1.loc[['Science', 'Hindi']])

print(dFrame1.loc['Maths'] > 90)


         Arnab  Ramit  Samridhi  Riya  Mallika
Maths       90     92        89    81       94
Science     91     81        91    71       95
Hindi       97     96        88    67       99
Arnab       False
Ramit        True
Samridhi    False
Riya        False
Mallika      True
Name: Maths, dtype: bool


In [6]:
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]
dtype = [('name', 'U10'), ('height', float), ('age', int)]
ar_5 = np.array(values, dtype=dtype)
print(ar_5, end = '\n\n')
ar_6 = np.sort(ar_5, order='age', kind='stable')
print(ar_6, end = '\n\n')



[('Arthur', 1.8, 41) ('Lancelot', 1.9, 38) ('Galahad', 1.7, 38)]

[('Galahad', 1.7, 38) ('Lancelot', 1.9, 38) ('Arthur', 1.8, 41)]



In [31]:

ResultSheet={
  'Arnab': pd.Series([90, 91, 97], index=['Maths','Science','Hindi']),
  'Ramit': pd.Series([92, 81, 96], index=['Maths','Science','Hindi']),
  'Samridhi': pd.Series([89, 91, 88], index=['Maths','Science','Hindi']), 
  'Riya': pd.Series([81, 71, 67], index=['Maths','Science','Hindi']),
  'Mallika': pd.Series([94, 95, 99], index=['Maths','Science','Hindi'])
}
dFrame1 = pd.DataFrame(ResultSheet)
print(dFrame1)
dFrame1 = dFrame1.drop('Maths', axis=0)
# dFrame1 = dFrame1.drop(['Samridhi','Ramit','Riya'], axis=1)
# print(dFrame1)
# del dFrame1['Arnab']
print(dFrame1)
 dFrame1.pop('Arnab')
print(dFrame1)






         Arnab  Ramit  Samridhi  Riya  Mallika
Maths       90     92        89    81       94
Science     91     81        91    71       95
Hindi       97     96        88    67       99
         Arnab  Ramit  Samridhi  Riya  Mallika
Science     91     81        91    71       95
Hindi       97     96        88    67       99
         Ramit  Samridhi  Riya  Mallika
Science     81        91    71       95
Hindi       96        88    67       99


In [35]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [5, 6, 7], 'C': [8, 9, 10]})
print("Id of original dataframe",id(df))
print(df)

df.drop('B',inplace = True, axis = 1)
print("Id of modified dataframe",id(df))
print(df)

Id of original dataframe 2394147578480
   A  B   C
0  1  5   8
1  2  6   9
2  3  7  10
Id of modified dataframe 2394147578480
   A   C
0  1   8
1  2   9
2  3  10


In [37]:
import numpy as np
import pandas as pd
# series_1 = pd.Series([1, 2, np.nan], dtype="Int64")
series_1 = pd.Series([1, 2, np.nan], dtype=pd.Int64Dtype())
print(series_1)


0       1
1       2
2    <NA>
dtype: Int64


In [38]:
print(pd.isna(None))  #True
print(pd.notna(None))


True
False


In [40]:
series_2 = pd.Series([1.5, 2.3, np.nan], dtype="Float64)
#is same as series_2 = pd.Series([1.5, 2.3, np.nan], dtype=pd.Float64Dtype())
print(series_2)


0    1.5
1    2.3
2    NaN
dtype: float64


In [41]:
import pandas as pd
import numpy as np

ser = pd.Series([2, np.nan, 3, np.nan])
print(ser, end = '\n\n')
print(ser.cumsum(), end = '\n\n')
print(ser.cumsum(skipna=False))



0    2.0
1    NaN
2    3.0
3    NaN
dtype: float64

0    2.0
1    NaN
2    5.0
3    NaN
dtype: float64

0    2.0
1    NaN
2    NaN
3    NaN
dtype: float64
