In [9]:
import numpy as np
ar_1 = np.array([[1, 2], [3, 4]])  #No of Rows: 2 No of Col.: 2
ar_2 = np.array([[5, 6]])  #No of Rows: 1 No of Col.: 2
ar_3 = np.concatenate((ar_1, ar_2), axis=0)
print(ar_3, end = '\n\n')
ar_4 = np.concatenate((ar_1, ar_2.T), axis=1)  #No of Rows: 2 No of Col.: 3
print(ar_4, end = '\n\n')
ar_5 = np.concatenate((ar_1, ar_2), axis=None)  #No of Rows: 1 No of Col.: 6
print(ar_5, end = '\n\n')



[[1 2]
 [3 4]
 [5 6]]

[[1 2 5]
 [3 4 6]]

[[5]
 [6]]
[1 2 3 4 5 6]



In [13]:
ar_6 = np.array((1,2,3))  #No of Rows: 1 No of Col.: 3
ar_7 = np.array((4,5,6))  #No of Rows: 1 No of Col.: 3
ar_8 = np.hstack((ar_6, ar_7))
print(ar_8)


[1 2 3 4 5 6]


In [14]:
import numpy as np
a = np.array([10, 20, 30])
b = np.array([[100, 200,3], [70, 90,4]])
c = np.hstack((a, b))
print(c.ndim + c.size)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [16]:

import numpy as np
ar_1 = np.arange(24.0).reshape(4, 6)
print(np.hsplit(ar_1, 2), end = "\n\n")
print(np.hsplit(ar_1, 3), end = "\n\n")
#print(np.hsplit(ar_1, 4))
print(np.vsplit(ar_1, 2), end = "\n\n")
print(np.vsplit(ar_1, 4), end = "\n\n")
#print(np.vsplit(ar_1, 3))



[array([[ 0.,  1.,  2.],
       [ 6.,  7.,  8.],
       [12., 13., 14.],
       [18., 19., 20.]]), array([[ 3.,  4.,  5.],
       [ 9., 10., 11.],
       [15., 16., 17.],
       [21., 22., 23.]])]

[array([[ 0.,  1.],
       [ 6.,  7.],
       [12., 13.],
       [18., 19.]]), array([[ 2.,  3.],
       [ 8.,  9.],
       [14., 15.],
       [20., 21.]]), array([[ 4.,  5.],
       [10., 11.],
       [16., 17.],
       [22., 23.]])]

[array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]]), array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])]

[array([[0., 1., 2., 3., 4., 5.]]), array([[ 6.,  7.,  8.,  9., 10., 11.]]), array([[12., 13., 14., 15., 16., 17.]]), array([[18., 19., 20., 21., 22., 23.]])]



In [17]:
ar_2 = np.arange(8)
print(np.split(ar_2, 2))
print(np.split(ar_2, 4))
print(np.split(ar_2, (2,6)))


[array([0, 1, 2, 3]), array([4, 5, 6, 7])]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]
[array([0, 1]), array([2, 3, 4, 5]), array([6, 7])]


In [18]:
a = np.arange(6).reshape(3, 2)
b = np.insert(a, 1, [[7],[8],[9]], axis=1)
print(b)

[[0 7 8 9 1]
 [2 7 8 9 3]
 [4 7 8 9 5]]


In [19]:
b = np.array([0, 1, 2, 3, 4, 5])
a = np.insert(b, [2, 2], [7.13, False])
print(a)



[0 1 7 0 2 3 4 5]


In [21]:
import numpy as np
ar_1 = np.array([[1,4],[3,1]])
ar_2 = np.sort(ar_1, axis = 1)
print(ar_2)


[[1 4]
 [1 3]]
