In [2]:

l1 = [1,2,3,4]
l2 = [4,3,2,1]
print(l1 + l2)

[1, 2, 3, 4, 4, 3, 2, 1]


In [13]:
import numpy as np

ar1 = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])
# print(ar1+ar2)
# print(ar1-ar2)
# print(ar1*ar2)
# print(ar1/ar2) 
# print(ar1%ar2)  
# print(ar1**ar2)  
print(ar1 < ar2)

[ True  True  True  True]


In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
result = a + b
print(result)


[[11 22 33]
 [14 25 36]]


In [15]:
ar_4 = np.array([[1, 2, 3], [4, 5, 6]]) 
ar_5 = np.reshape(ar_4 , -1)
print(ar_5)


[1 2 3 4 5 6]


In [17]:
ar_6 = np.arange(0, 16)
print(ar_6)
ar_7 = np.reshape(ar_6, (4, 4))
print(ar_7)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [19]:
a = np.zeros((16, ))
b = np.reshape(a, (3,5))
print(a)
print(b)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [26]:
ar_8 = np.array([[1, 2, 3], [4, 5, 6]])
ar_9 = np.resize(ar_8 , (3, 8))
print(ar_9)
ar_14 = ar_9.flatten()
print(ar_14)
ar_15 = np.transpose(ar_8)
print(ar_15)



[[1 2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3 4]
 [5 6 1 2 3 4 5 6]]
[1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [31]:
ar_1 = np.array([[1, 2], [3, 4]]) 
ar_2 = np.array([[5, 6]]) 
ar_3 = np.concatenate((ar_1, ar_2))
print(ar_3)


[[1 2]
 [3 4]
 [5 6]]
