In [3]:
import numpy as np

a = np.arange(15, 4, -2) 
print(a)
print(a[6:0:-2])



[15 13 11  9  7  5]
[ 5  9 13]


In [4]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
print(l1 + l2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [7]:
l1 = np.array([1,2,3,4]) 
l2 =np.array([5,6,7,8])
print(l1 + l2)
print(l1 - l2)
print(l1 / l2)
print(l1 * l2)
print(l1 % l2)
print(l1 ** l2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[0.2        0.33333333 0.42857143 0.5       ]
[ 5 12 21 32]
[1 2 3 4]
[    1    64  2187 65536]


In [8]:
l1 = np.array([[1,2,3,4], [9,8,7,6]]) 
l2 =np.array([5,6,7,8])
print(l1 + l2)

[[ 6  8 10 12]
 [14 14 14 14]]


In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[10], [20]])
result = a + b
print(result)


[[11 12 13]
 [24 25 26]]


In [11]:
ar_2 = np.array([[4, 3],[2, 1]])
ar_3 = np.array([[5, 4], [3, 2]])
print(ar_2 == ar_3, end = '\n\n')
print(ar_2 != ar_3, end = '\n\n')
print(ar_2 >= ar_3, end = '\n\n')
print(ar_2 <= ar_3, end = '\n\n')
print(ar_2 > ar_3, end = '\n\n')
print(ar_2 < ar_3, end = '\n\n')



[[False False]
 [False False]]

[[ True  True]
 [ True  True]]

[[False False]
 [False False]]

[[ True  True]
 [ True  True]]

[[False False]
 [False False]]

[[ True  True]
 [ True  True]]



In [14]:
ar_4 = np.array([[1, 2, 3], [4, 5, 6]])
ar_5 = np.reshape(ar_4 , -1)
print(ar_5)


[1 2 3 4 5 6]


In [18]:
ar_6 = np.arange(0, 16)
print(ar_6)
ar_7 = np.reshape(ar_6, (4, 4))
print(ar_7)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [22]:
ar_8 = np.array([[1, 2, 3], [4, 5, 6]])
ar_9 = np.resize(ar_8 , (6, 8))
print(ar_9)


[[1 2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3 4]
 [5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3 4]
 [5 6 1 2 3 4 5 6]]
