In [1]:
print('Hello')

Hello


In [6]:
import numpy as np

ar_1 = np.array([10, 20, 'abc'])
print(ar_1)

l1 = [1,2,3]
print(l1)



['10' '20' 'abc']
[1, 2, 3]


In [7]:
ar_2 = np.array([10, 20, 30, 40, 50], dtype = float)
print(ar_2)


[10. 20. 30. 40. 50.]


In [16]:
ar_4 = np.array([[10,20],[30,40]])
print(ar_4)
print("The dimension of ", ar_4, "is", ar_4.ndim)


[[10 20]
 [30 40]]
The dimension of  [[10 20]
 [30 40]] is 2


In [9]:
ar_5 = np.zeros(3)
print(ar_5)


[0. 0. 0.]


In [10]:
ar_6 = np.zeros((3,4))
print(ar_6)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
ar_7 = np.ones(5)
print(ar_7)


[1. 1. 1. 1. 1.]


In [12]:
ar_8 = np.ones((2,3))
print(ar_8)


[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
ar_9 = np.arange(6)
print(ar_9)


[0 1 2 3 4 5]


In [14]:
ar_10 = np.arange(2, 15, 3)
print(ar_10)


[ 2  5  8 11 14]


In [19]:
a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [21]:
ar_4 = np.array([[10,20],[30,40]])
print(ar_4.shape)
print(ar_4.size)

(2, 2)
4


In [26]:
a = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(a.dtype)



int64


In [35]:
ar_11 = np.arange(10, 25, 2)
print(ar_11)
print("ar_11[1] =",ar_11[-1])
print("ar_11[1 : ar_11.size : 2] =", ar_11[ar_11.size - 1 : 0 : -2])




[10 12 14 16 18 20 22 24]
ar_11[1] = 24
ar_11[1 : ar_11.size : 2] = [24 20 16 12]


In [37]:
ar_12 = np.array([np.arange(21, 10, -2), np.arange(10, -1, -2), np.zeros(6, dtype = np.int64)])
print(ar_12)
print("ar_12[0, 0] =",ar_12[0, 0]) # 21
print("ar_12[0, 0:6:2] =",ar_12[0, 0:6:2]) 



[[21 19 17 15 13 11]
 [10  8  6  4  2  0]
 [ 0  0  0  0  0  0]]
ar_12[0, 0] = 21
ar_12[0, 0:6:2] = [21 17 13]
