In [1]:
import numpy as np
import pandas as pd


dFrame4 = pd.DataFrame(
  {
    'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col2': [2, 1, 9, 8, 7, 4],
    'col3': [0, 1, 9, 4, 2, 3],
    'col4': ['a', 'B', 'c', 'D', 'e', 'F']
  }
)
print("Original:\n", dFrame4, sep = "")


Original:
  col1  col2  col3 col4
0    A     2     0    a
1    A     1     1    B
2    B     9     9    c
3  NaN     8     4    D
4    D     7     2    e
5    C     4     3    F


In [2]:
arr_1 = np.arange(10)
print(np.where(arr_1 < 5, arr_1, 10 * arr_1))


[ 0  1  2  3  4 50 60 70 80 90]


In [4]:
arr_2 = np.array([[0, 1, 2], [0, 2, 4], [0, 3, 6]])
print(arr_2)
print(np.where(arr_2 < 4, arr_2, -1))

[[0 1 2]
 [0 2 4]
 [0 3 6]]
[[ 0  1  2]
 [ 0  2 -1]
 [ 0  3 -1]]


In [5]:
s = pd.Series(range(5))
s.where(s > 0)


0    NaN
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float64

In [6]:
s = pd.Series(range(5))
s.mask(s > 0)


0    0.0
1    NaN
2    NaN
3    NaN
4    NaN
dtype: float64

In [9]:
dFrame1 = pd.DataFrame(np.arange(10).reshape(-1, 2), columns=['A', 'B'])
print(dFrame1)
print(dFrame1.where(dFrame1 % 3 == 0, -dFrame1))
print(dFrame1.mask(dFrame1 % 3 == 0, -dFrame1))

   A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9
   A  B
0  0 -1
1 -2  3
2 -4 -5
3  6 -7
4 -8  9
   A  B
0  0  1
1  2 -3
2  4  5
3 -6  7
4  8 -9


In [13]:
index = pd.MultiIndex.from_tuples([
    ('Math', 'Test1'),
    ('Math', 'Test2'),
    ('Science', 'Test1'),
    ('Science', 'Test2')
], names=['Subject', 'Test'])
dFrame2 = pd.DataFrame({
    'Riya': [90, 88, 92, 85],
    'Ramit': [86, 89, 94, 90]
}, index=index)

print(dFrame2)
print("Row index levels:", dFrame2.index.nlevels)
print("Row index names:", dFrame2.index.names)
print(dFrame2.loc['Math'])

print(dFrame2.xs('Test1', level='Test'))



               Riya  Ramit
Subject Test              
Math    Test1    90     86
        Test2    88     89
Science Test1    92     94
        Test2    85     90
Row index levels: 2
Row index names: ['Subject', 'Test']
       Riya  Ramit
Test              
Test1    90     86
Test2    88     89
         Riya  Ramit
Subject             
Math       90     86
Science    92     94
