In [1]:
import numpy as np
import pandas as pd
print(np.__version__)
print(pd.__version__)

2.0.2
2.2.3


In [7]:
ar_1 = np.array([10,20,30, 'a'])
ar_2 = np.array([10,20,30] , dtype = float)
l = [1,2,3]
print(ar_1, ar_2)
print(l)

['10' '20' '30' 'a'] [10. 20. 30.]
[1, 2, 3]


In [13]:
ar_3 = np.zeros(3)
ar_4 = np.zeros((3,3))
print(ar_3)
print(ar_4)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
arr= [[[1,2],[3,4],[5,6]], [[1,2],[3,4],[5,6]]]

In [14]:
ar_5 = np.ones(3)
ar_6 = np.ones((3,3))
print(ar_5)
print(ar_6)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
arr = np.arange(1,10,2)
arr1 = np.arange(5)
print(arr1, arr1.ndim)
print(arr)

[0 1 2 3 4] 1
[1 3 5 7 9]


In [28]:
arr = np.ones((2,3))
print(arr, arr.ndim, arr.shape, arr.size, arr.dtype, arr.itemsize)

[[1. 1. 1.]
 [1. 1. 1.]] 2 (2, 3) 6 float64 8


In [26]:
ar_1 = np.array([10,20,30, 'a'])
print(ar_1.shape, ar_1.dtype)

(4,) <U21


In [33]:
ar_11 = np.arange(10, 25, 2)
print(ar_11)
print(ar_11[-1])
print(ar_11[1 : ar_11.size : 2])
print(ar_l1[ar_11.size - 1 : 0 : -2])

[10 12 14 16 18 20 22 24]
24
[12 16 20 24]


In [38]:
ar_12 = np.array([np.arange(21, 10, -2), np.arange(10, -1, -2), np.zeros(6, dtype = np.int64)])
print(ar_12)
print(ar_12[0, 0:6:2])


[[21 19 17 15 13 11]
 [10  8  6  4  2  0]
 [ 0  0  0  0  0  0]]
[21 17 13]
