In [3]:
import numpy as np
import pandas as pd

dFrame1 = pd.DataFrame(
    {
        'consumption': [10.51, 103.11, 55.48],
        'co2_emissions': [37.2, 19.66, 1712]
    },
    index=['A', 'B', 'C']
)
print(dFrame1)
print(dFrame1.idxmin(), end = '\n\n')
print(dFrame1.idxmax())



   consumption  co2_emissions
A        10.51          37.20
B       103.11          19.66
C        55.48        1712.00
consumption      A
co2_emissions    B
dtype: object

consumption      B
co2_emissions    C
dtype: object


In [6]:
dFrame3 = pd.DataFrame(
  {
    'month': [1, 4, 7, 10],
    'year': [2012, 2014, 2013, 2014],
    'sale': [55, 40, 84, 31]
  }
)
print("The original dataframe has shape:", dFrame3.shape)
print("The original dataframe is\n", dFrame3, sep = "")

dFrame3 = dFrame3.set_index('month')
print("The modified dataframe has shape:", dFrame3.shape)
print("The modified dataframe is\n", dFrame3, sep = "")



The original dataframe has shape: (4, 3)
The original dataframe is
   month  year  sale
0      1  2012    55
1      4  2014    40
2      7  2013    84
3     10  2014    31
The modified dataframe has shape: (4, 2)
The modified dataframe is
       year  sale
month            
1      2012    55
4      2014    40
7      2013    84
10     2014    31


In [7]:
arr_1 = np.arange(10)
print(np.where(arr_1 < 5, arr_1, 10 * arr_1))


[ 0  1  2  3  4 50 60 70 80 90]


In [9]:
arr_2 = np.array([[0, 1, 2], [0, 2, 4], [0, 3, 6]])
print(arr_2)
print(np.where(arr_2 < 4, arr_2, -1))


[[0 1 2]
 [0 2 4]
 [0 3 6]]
[[ 0  1  2]
 [ 0  2 -1]
 [ 0  3 -1]]


In [12]:
s = pd.Series(range(5))
print(s)
s.where(s > 0)
s = pd.Series(range(5))
s.mask(s > 0)


0    0
1    1
2    2
3    3
4    4
dtype: int64


0    0.0
1    NaN
2    NaN
3    NaN
4    NaN
dtype: float64

In [15]:
dFrame1 = pd.DataFrame(np.arange(10).reshape(-1, 2), columns=['A', 'B'])
print(dFrame1)
print(dFrame1.where(dFrame1 % 3 == 0, -dFrame1))
print(dFrame1.mask(dFrame1 % 3 == 0, -dFrame1))

   A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9
   A  B
0  0 -1
1 -2  3
2 -4 -5
3  6 -7
4 -8  9
   A  B
0  0  1
1  2 -3
2  4  5
3 -6  7
4  8 -9


In [22]:
index = pd.MultiIndex.from_tuples([
    ('Math', 'Test1'),
    ('Math', 'Test2'),
    ('Science', 'Test1'),
    ('Science', 'Test2')
], names=['Subject', 'Test'])

dFrame2 = pd.DataFrame({
    'Riya': [90, 88, 92, 85],
    'Ramit': [86, 89, 94, 90]
}, index=index)

print(dFrame2)
print("Row index levels:", dFrame2.index.nlevels)
print("Row index names:", dFrame2.index.names)
print("Row columns levels:", dFrame2.columns.nlevels)
print("Row columns names:", dFrame2.columns)

# print(dFrame2.loc['Math'])
# print(dFrame2['Riya'])
print(dFrame2.xs('Test1', level='Test'))

               Riya  Ramit
Subject Test              
Math    Test1    90     86
        Test2    88     89
Science Test1    92     94
        Test2    85     90
Row index levels: 2
Row index names: ['Subject', 'Test']
Row columns levels: 1
Row columns names: Index(['Riya', 'Ramit'], dtype='object')
         Riya  Ramit
Subject             
Math       90     86
Science    92     94
