In [4]:
import numpy as np
ar_1 = np.arange(24.0).reshape(4, 6)
print(ar_1)
print(np.vsplit(ar_1, 4), end = "\n\n")



[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[array([[0., 1., 2., 3., 4., 5.]]), array([[ 6.,  7.,  8.,  9., 10., 11.]]), array([[12., 13., 14., 15., 16., 17.]]), array([[18., 19., 20., 21., 22., 23.]])]



In [10]:
ar_2 = np.arange(8)
print(np.split(ar_2, 2))
print()
print(np.split(ar_2, (2,6)))



[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

[array([0, 1]), array([2, 3, 4, 5]), array([6, 7])]


In [11]:
ar_3 = np.arange(16).reshape(4, 4)
print(np.split(ar_3, 2))
print(np.split(ar_3, 2, axis = 1))
print()
print(np.split(ar_3, [1, 4]))


[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([], shape=(0, 4), dtype=int64)]


In [12]:
ar_4 = np.arange(8.0)
print(np.array_split(ar_4, 3))



[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]


In [16]:
ar_5 = np.arange(12).reshape((3, 4))
print(np.array_split(ar_5, 4))
print(np.array_split(ar_5, 3, axis = 1))


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([], shape=(0, 4), dtype=int64)]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [17]:

ar_1 = np.arange(1, 4)
ar_2 = np.arange(4, 10).reshape(2,3)
ar_3 = np.append(ar_1, ar_2)
print(ar_3)


[1 2 3 4 5 6 7 8 9]


In [18]:
ar_4 = np.arange(1, 7).reshape(2, 3)
ar_5 = np.arange(7, 10).reshape(1, 3)
ar_6 = np.append(ar_4, ar_5, axis=0)
print(ar_6)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
ar_7 = np.array([[1, 2], [3, 4]])
ar_8 = np.array([[5], [6]])
result = np.append(ar_7, ar_8, axis=1)
print(result)


[[1 2 5]
 [3 4 6]]


In [20]:

ar_10 = np.insert(ar_9, 1, 6)
print(ar_10)


[0 6 1 2 3 4 5]


In [21]:
ar_9 = np.arange(6).reshape(3, 2)
ar_11 = np.insert(ar_9, 1, 6, axis=1)
print(ar_11)


[[0 6 1]
 [2 6 3]
 [4 6 5]]


In [23]:
ar_9 = np.arange(6).reshape(3, 2)
ar_12 = np.insert(ar_9, [1], [[7],[8],[9]], axis=1)
print(ar_12 )
a = np.arange(6).reshape(3, 2)
b = np.insert(a, 1, [[7],[8],[9]], axis=1)
print(b)



[[0 7 1]
 [2 8 3]
 [4 9 5]]
[[0 7 8 9 1]
 [2 7 8 9 3]
 [4 7 8 9 5]]


In [24]:
ar_13 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
ar_14 = np.delete(ar_13, 1, axis = 0)
print(ar_14)


[[ 1  2  3  4]
 [ 9 10 11 12]]


In [25]:
a = np.arange(1, 13).reshape(3, 4)
b = np.delete(a, [1,3,5], None)
print(b)


[ 1  3  5  7  8  9 10 11 12]
